channels:
- conda-forge
dependencies:
- python == 3.10.8
- av
- bokeh >=3.1.1
- coverage
- cython
- h5py
- holoviews >=1.16.2
- ipykernel
- ipython
- ipyparallel
- jupyter
- jupyter_bokeh
- matplotlib
- moviepy
- mypy
- nose
- numpy == 1.26.3
- numpydoc
- opencv
- panel >=1.0.2
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy == 1.11.4
- tensorflow == 2.10.0
- tifffile
- tk
- tqdm
- yapf
- zarr
